/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;

/**
 *
 * @author Erika
 */
public class FRM_Migracion extends javax.swing.JFrame {

Controlador controlador;
int numero=0;

    public FRM_Migracion() {
        initComponents();
        setLocation(400,200);
        setVisible(false);
        this.controlador=new Controlador(this);
        agregarEventos();
    }
    
    public void agregarEventos()
    {
        this.btn_NuevaFicha.addActionListener(controlador);
        this.btn_Eliminar.addActionListener(controlador);
        this.btn_Modificar.addActionListener(controlador);
        this.btn_Promedio.addActionListener(controlador);
        this.btn_MenorMayor.addActionListener(controlador);
        this.btn_Siguiente.addActionListener(controlador);    
    }
    
    public void limpiarDatos()
      {
          this.jt_Nombre.setText("");
          this.jt_Cedula.setText("");
          this.jt_Edad.setText("");
          this.jt_Fecha.setText("");
      }
    
      public String enviarInformacionNombre()
    {
        String nombre="";
        nombre=jt_Nombre.getText();
        return nombre;
    }
      
      public String enviarInformacionEdad()
    {
        String edad;
        edad=jt_Edad.getText();
        return edad;
    }
      
      public String enviarInformacionCedula()
      {
          String cedula;
          cedula=jt_Cedula.getText();
          return cedula;
      }
      
       public String enviarInformacionFecha()
      {
          String fecha;
          fecha=jt_Cedula.getText();
          return fecha;
      }
      
        public int enviarPrioridad()
    {
        int datos=0;
        if(jrb_Normal.isSelected())
        {
            datos=1;
        }
        else
        {
            if(jrb_Preferencial.isSelected())
            {
                datos=2;
            }
        }
        
        return datos;
    }
       
        
         public void imprimirArea(String texto)
    {
        this.jta_Informacion.setText(texto);
    }
  public void setCita(int numero)
       {
           jt_NumFicha.setText(""+numero); 
       }
     
       public int aumento()
       {
           
           numero++;
           
           return numero;
       }
       
       public String getFicha()
       {
           return this.jt_NumFicha.getText();
       }
       
       
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Cedula = new javax.swing.JTextField();
        jt_Edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_Fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jl_TipoFicha = new javax.swing.JLabel();
        jrb_Preferencial = new javax.swing.JRadioButton();
        jrb_Normal = new javax.swing.JRadioButton();
        jl_Actual = new javax.swing.JLabel();
        btn_Siguiente = new javax.swing.JButton();
        btn_MenorMayor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Informacion = new javax.swing.JTextArea();
        btn_NuevaFicha = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Promedio = new javax.swing.JButton();
        btn_MayorMenor = new javax.swing.JButton();
        jt_NumFicha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Costa-Rica-Gobierno-Republica-IV_LNCIMA20151015_0164_22.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(217, 0, 223, 163);

        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 197, 54, 16);

        jLabel3.setText("Cedula:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 233, 44, 16);

        jLabel4.setText("Edad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 270, 33, 16);
        getContentPane().add(jt_Nombre);
        jt_Nombre.setBounds(128, 194, 191, 22);

        jt_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jt_Cedula);
        jt_Cedula.setBounds(128, 230, 191, 22);

        jt_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_EdadActionPerformed(evt);
            }
        });
        getContentPane().add(jt_Edad);
        jt_Edad.setBounds(128, 267, 80, 22);

        jLabel5.setText("Fecha de Cita:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(23, 310, 83, 16);

        jt_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_FechaActionPerformed(evt);
            }
        });
        getContentPane().add(jt_Fecha);
        jt_Fecha.setBounds(128, 307, 191, 22);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 194, 0, 0);

        jl_TipoFicha.setText("Tipo de Ficha");
        getContentPane().add(jl_TipoFicha);
        jl_TipoFicha.setBounds(478, 194, 77, 16);

        jrb_Preferencial.setText("Preferencial (Ley 7600)");
        getContentPane().add(jrb_Preferencial);
        jrb_Preferencial.setBounds(478, 219, 161, 25);

        jrb_Normal.setText("Normal");
        getContentPane().add(jrb_Normal);
        jrb_Normal.setBounds(478, 249, 69, 25);

        jl_Actual.setText("Ficha:");
        getContentPane().add(jl_Actual);
        jl_Actual.setBounds(30, 360, 74, 16);

        btn_Siguiente.setText("Siguiente Ficha");
        getContentPane().add(btn_Siguiente);
        btn_Siguiente.setBounds(470, 360, 119, 25);

        btn_MenorMayor.setText("<");
        getContentPane().add(btn_MenorMayor);
        btn_MenorMayor.setBounds(470, 390, 41, 25);

        jta_Informacion.setColumns(20);
        jta_Informacion.setRows(5);
        jScrollPane1.setViewportView(jta_Informacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(23, 487, 616, 151);

        btn_NuevaFicha.setText("Nueva Ficha");
        btn_NuevaFicha.setActionCommand("NuevaFicha");
        btn_NuevaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevaFichaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_NuevaFicha);
        btn_NuevaFicha.setBounds(50, 450, 101, 25);

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Eliminar);
        btn_Eliminar.setBounds(370, 450, 79, 25);

        btn_Modificar.setText("Modificar");
        getContentPane().add(btn_Modificar);
        btn_Modificar.setBounds(490, 450, 85, 25);

        btn_Promedio.setText("Promedio");
        btn_Promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PromedioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Promedio);
        btn_Promedio.setBounds(240, 450, 87, 25);

        btn_MayorMenor.setText(">");
        getContentPane().add(btn_MayorMenor);
        btn_MayorMenor.setBounds(520, 390, 41, 25);

        jt_NumFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NumFichaActionPerformed(evt);
            }
        });
        getContentPane().add(jt_NumFicha);
        jt_NumFicha.setBounds(30, 380, 70, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CedulaActionPerformed

    private void jt_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_EdadActionPerformed

    private void jt_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_FechaActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_NuevaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevaFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NuevaFichaActionPerformed

    private void btn_PromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PromedioActionPerformed

    private void jt_NumFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NumFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NumFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Migracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_MayorMenor;
    private javax.swing.JButton btn_MenorMayor;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_NuevaFicha;
    private javax.swing.JButton btn_Promedio;
    private javax.swing.JButton btn_Siguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_Actual;
    private javax.swing.JLabel jl_TipoFicha;
    private javax.swing.JRadioButton jrb_Normal;
    private javax.swing.JRadioButton jrb_Preferencial;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Fecha;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_NumFicha;
    private javax.swing.JTextArea jta_Informacion;
    // End of variables declaration//GEN-END:variables
}
